### ISSUE TITLE
Неработающий навык - Невидимость

### ISSUE THREAD

**Issue by Z-RAY-Z** [Rabb1tof/NCRPG#11]
Версия NC:RPG 1.3.8.6, SM 6492.
Навык Невидимость никак не проявляет себя - игроки не меняют свою прозрачность.
На сервере присутствует spawn_protection который в начале раунда на несколько секунд делает игроков прозрачными, а потом ставит по-умолчанию.
Я думаю, что в этом проблема - NCRPG ТОЛЬКО при спавне игрока ставит ему прозрачность.
Предлагаю сделать как в SM:RPG - https://github.com/peace-maker/smrpg/blob/master/scripting/upgrades/smrpg_upgrade_stealth.sp
Установка инвиза каждые n-секунд позволит свести на нет влияние сторонних плагинов, авто-установка sv_disable_immunity_alpha избавит от вопросов от назойливых рукожопов, а установка альфы на child-предметы добавит эстетики)

**Comment by Rabb1tof** [comment]
@Z-RAY-Z, если имеется возможность, глянь наличие бага без `spawn_protection`.

**Comment by Z-RAY-Z** [comment]
С отключенным спавн_протектором работает. Периодическое обновление инвиза на игроках лишним не будет.

**Comment by WhyFaust** [comment]
По сути можно использовать в плагине https://forums.alliedmods.net/showthread.php?t=169795 и хукать изменение прозрачности. Если изменена - вернуть обратно.
