### ISSUE TITLE
Проблемы со скиллами.

### ISSUE THREAD

**Issue by Truyn** [Rabb1tof/NCRPG#15]
Проблема со скиллом урона( не работает при дефолтных настройках)
Так же не работают,вампиризм,ударная волна.
Из тех что выявлены.

**Comment by Truyn** [comment]
Версия sourcemod 6492

**Comment by Truyn** [comment]
Вампиризм я починил,перекомпиляцией на последнем sm версии с гитхаба.
А вот ударная волна,возрождение,по прежнему не пашут.

**Comment by Truyn** [comment]
![image](https://user-images.githubusercontent.com/53527324/93770554-0076da00-fc25-11ea-80d7-f7529b5a91fc.png)

**Comment by Rabb1tof** [comment]
закрыт по причине, что все перейдет в одну карточку - #17
