### ISSUE TITLE
Много проблем и недочетов будут фиксы?

### ISSUE THREAD

**Issue by Truyn** [Rabb1tof/NCRPG#20]
ИЛИ ВСЕ ББ МОДУ МОЖНО ЗАБЫТЬ?

**Comment by Rabb1tof** [comment]
На хл ставил тег "не поддерживается ", в основном всё в руках сообщества, когда возможность есть - занимаюсь.

**Comment by Truyn** [comment]
> На хл ставил тег "не поддерживается ", в основном всё в руках сообщества, когда возможность есть - занимаюсь.

Понял, ну там не так уж и много поправлять, но хотелось бы все же.


К примеру тяжелые пули вообще не работают.

И проценты прокачки скиллов как же уебански сделано.
Почему нельзя по 100% системе, а не вот эти блядь петушиные 0.005000  и тд.

**Comment by Truyn** [comment]
Никакой документации и описания, причем на некоторых скиллах типо 1.5 это будет 1.5% а на некоторых 150%.

**Comment by Truyn** [comment]
У меня горит жопа от того что даже когда им занимались нельзя было сделать нормальную структуру и пояснения что где и как качается, все нахуй каждый скилл методом тыка надо проверять
