### ISSUE TITLE
Некорректная работа модулей и ошибки.

### ISSUE THREAD

**Issue by junkees** [Rabb1tof/NCRPG#6]
Когда загружаешься на сервер, в консоли высвечивается ошибка связанная с mysql

[NCRPG/NCRPG.smx] Could not remove players, reason: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1

Модуль ncrpg_skill_gravity и ncrpg_skill_speed работает, но в начале раунда перестает.
Т.е ты покупаешь в rpg меню гравитацию, все работает, начинается новый раунд и перестает до тех пор пора не продашь один лвл скилла или же купишь.

При выходе с сервера пишет
Error save Player kefir . Player is not load..
Хз, ошибка ли. Использовал как mysql так и sqlite

**Comment by junkees** [comment]
Ошибок в логах насчет модулей нет. Они просто не работают в начале раунда.

**Comment by Rabb1tof** [comment]
Ошибку запроса выловить не смог как на sqlite, так и на mysql (5.5.62).
Баги со скиллами поправил в [этом](https://github.com/Rabb1tof/NCRPG/commit/bcaf5f8f0520c888e13e0eaa21c961c511f57725) коммите.
